import { Sidebar } from "@/components/ui/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex h-screen">
      <Sidebar className="h-screen sticky top-0" />
      <main className="flex-1 overflow-y-auto">{children}</main>
    </div>
  );
}
